# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unpause < Formula
  desc "One list of every Claude Code session on your machine. Pick one, it opens where it left off."
  homepage "https://github.com/hamzafer/unpause"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hamzafer/unpause/releases/download/v0.4.0/unpause_0.4.0_darwin_amd64.tar.gz"
      sha256 "2f9f608ab49e44d00b6de58014c0de98e95a7d3bf25e3f9f44eeccb8ebce0b61"

      define_method(:install) do
        bin.install "unpause"
        bash_completion.install "completions/unpause.bash" => "unpause"
        zsh_completion.install "completions/unpause.zsh" => "_unpause"
        fish_completion.install "completions/unpause.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hamzafer/unpause/releases/download/v0.4.0/unpause_0.4.0_darwin_arm64.tar.gz"
      sha256 "e908dea7d9151177ecec33f282749c66efcfa109ecedaec4f509767d048b8e8c"

      define_method(:install) do
        bin.install "unpause"
        bash_completion.install "completions/unpause.bash" => "unpause"
        zsh_completion.install "completions/unpause.zsh" => "_unpause"
        fish_completion.install "completions/unpause.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hamzafer/unpause/releases/download/v0.4.0/unpause_0.4.0_linux_amd64.tar.gz"
      sha256 "18963f109b58b1bd640dfb6a4eea68c440ae72afe13cca4aeecaffabb26f6965"
      define_method(:install) do
        bin.install "unpause"
        bash_completion.install "completions/unpause.bash" => "unpause"
        zsh_completion.install "completions/unpause.zsh" => "_unpause"
        fish_completion.install "completions/unpause.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hamzafer/unpause/releases/download/v0.4.0/unpause_0.4.0_linux_arm64.tar.gz"
      sha256 "87d876d155cfbd6988f74df892d7c77fdaf07810060930a0fd132ddb6e363469"
      define_method(:install) do
        bin.install "unpause"
        bash_completion.install "completions/unpause.bash" => "unpause"
        zsh_completion.install "completions/unpause.zsh" => "_unpause"
        fish_completion.install "completions/unpause.fish"
      end
    end
  end

  test do
    system "#{bin}/unpause", "--version"
  end
end
