# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unpause < Formula
  desc "One list of every Claude Code session on your machine. Pick one, it opens where it left off."
  homepage "https://github.com/hamzafer/unpause"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hamzafer/unpause/releases/download/v0.1.0/unpause_0.1.0_darwin_amd64.tar.gz"
      sha256 "022eb7f84f231804541be52b85fb19ad3a43fc6fe5d8b081c0741dbd454fa8d4"

      define_method(:install) do
        bin.install "unpause"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hamzafer/unpause/releases/download/v0.1.0/unpause_0.1.0_darwin_arm64.tar.gz"
      sha256 "b8716fb6bd4618415ba3693f19c03cebda252a61fd84e212fc03ff4bba80ccd0"

      define_method(:install) do
        bin.install "unpause"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hamzafer/unpause/releases/download/v0.1.0/unpause_0.1.0_linux_amd64.tar.gz"
      sha256 "c87fc7416aea7aab2ffa60a23445214fb72ad541d6739f24fc7852f54999db5a"
      define_method(:install) do
        bin.install "unpause"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hamzafer/unpause/releases/download/v0.1.0/unpause_0.1.0_linux_arm64.tar.gz"
      sha256 "eb2564a5c8f4488fb66aad5d47cc726875ad02cdf544b0e6654dc4c3df74fa68"
      define_method(:install) do
        bin.install "unpause"
      end
    end
  end

  test do
    system "#{bin}/unpause", "--version"
  end
end
